version: '3'

services:
  api:
    image: lottery-system-api
    links:
      - postgres
    build:
      context: ./api/
      dockerfile: Dockerfile.local
    ports:
      - ${LOTTERY_API_PORT}:${LOTTERY_API_PORT}
    volumes:
      - ./api:/usr/src/app
      - ./log/api:/usr/src/app/log/api
    environment:
      - PORT=${LOTTERY_API_PORT}
      - GAME_MILLISECOND=${LOTTERY_API_GAME_MILLISECOND}
      - DB_HOST=postgres
      - DB_USER=${LOTTERY_DB_USER}
      - DB_PASSWORD=${LOTTERY_DB_PASSWORD}
      - DB_NAME=${LOTTERY_DB_NAME}

  postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      TZ: Asia/Hong_Kong
      POSTGRES_USER: ${LOTTERY_DB_USER}
      POSTGRES_PASSWORD: ${LOTTERY_DB_PASSWORD}
      POSTGRES_DB: ${LOTTERY_DB_NAME}
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    links:
      - postgres
    ports:
      - ${LOTTERY_ADMINER_PORT}:8080